backend:
  name: git-gateway
  branch: feature/adding-anchor-tags
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# local_backend: true # Optional if you want to use the local proxy mode

publish_mode: editorial_workflow
media_folder: media    # I'm not using these default media directories at the moment.
public_folder: /media

collections:
  - name: "posts"
    label: "Home Page"
    folder: "content/blog"
    create: true
    delete: true
    path: "{{slug}}/index"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "./"
    public_folder: "./"
    fields:
      - { label: "Title", name: "title", widget: "string" }      
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Excerpt", name: "description", widget: "string", required: false }    
      - { label: "Image", name: "hero", widget: "image", required: false}
      - { label: "Video", name: "hero_video", widget: "file", required: false}
      - { label: "Section", name: "section", widget: "hidden", default: "home", required: true}
      - { label: "Priority", name: "priority", widget: "number", valueType: "int", required: true}
      - { label: "Author", name: "author", widget: "string", required: true}
      - label: "Type"
        name: "type"
        widget: "select"
        options: 
          - { label: "Image Quote 2 Column", value: "image_2_col"}
          - { label: "Image Quote 3 Column", value: "image_3_col"}
          - { label: "Video", value: "video"}
          - { label: "normal", value: "normal"}
        required: true
      - { label: "Col1", name: "col1", widget: "list", required: false}        
      - { label: "Col2", name: "col2", widget: "list", required: false}        
      - { label: "Body", name: "body", widget: "markdown", required: false}
       
  - name: "rta-journal"
    label: "RTA Journal"
    folder: "content/blog/rta-journal"
    create: true
    delete: true
    path: "{{slug}}/index"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "./"
    public_folder: "./"
    fields:
      - { label: "Title", name: "title", widget: "string" }      
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Excerpt", name: "description", widget: "string", required: false }    
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "musings-and-memories"
    label: "Musings and Memories"
    folder: "content/blog/musings-and-memories"
    create: true
    delete: true
    path: "{{slug}}/index"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "./"
    public_folder: "./"
    fields:
      - { label: "Title", name: "title", widget: "string" }      
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Excerpt", name: "description", widget: "string", required: false }    
      - { label: "Body", name: "body", widget: "markdown" }